--
-- DATABASE SETUP COMMANDS GIT GOOD
--



--
-- TABLES
--

--
-- Name: users; Type: TABLE;
--

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT,
  email TEXT,
  gender_identity TEXT,
  sexual_orientation TEXT,
  note TEXT,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  created TIMESTAMPTZ NOT NULL DEFAULT now() NOT NULL
);

--
-- Name: posts; Type: TABLE;
--

CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  file_id INTEGER,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  created TIMESTAMPTZ DEFAULT now() NOT NULL
);

--
-- Name: comments; Type: TABLE;
--

CREATE TABLE comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  file_id INTEGER,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  created TIMESTAMPTZ DEFAULT now() NOT NULL
);

--
-- Name: votes; Type: TABLE;
--

CREATE TABLE votes (
  user_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  liked BOOLEAN NOT NULL,
  created TIMESTAMPTZ DEFAULT now() NOT NULL
);

--
-- Name: files; Type: TABLE;
--

CREATE TABLE files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  url TEXT NOT NULL,
  created TIMESTAMPTZ DEFAULT now() NOT NULL
);

--
-- PRIMARY KEYS
--

--
-- Name: users_pkey; Type: PK CONSTRAINT;
--

ALTER TABLE ONLY users
  ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: posts_pkey; Type: PK CONSTRAINT;
--

ALTER TABLE ONLY posts
  ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

--
-- Name: comments_pkey; Type: PK CONSTRAINT;
--

ALTER TABLE ONLY comments
  ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

--
-- Name: votes_pkey; Type: PK CONSTRAINT;
--

ALTER TABLE ONLY votes
  ADD CONSTRAINT votes_pkey PRIMARY KEY (user_id, post_id);

--
-- Name: files_pkey; Type: PK CONSTRAINT;
--

ALTER TABLE ONLY files
  ADD CONSTRAINT files_pkey PRIMARY KEY (id);



--
-- FOREIGN KEYS
--

--
-- Name: posts_user_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY posts
  ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: posts_file_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY posts
  ADD CONSTRAINT posts_file_id_fkey FOREIGN KEY (file_id) REFERENCES files(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: comments_user_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY comments
  ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: comments_post_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY comments
  ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: comments_file_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY comments
  ADD CONSTRAINT comments_file_id_fkey FOREIGN KEY (file_id) REFERENCES files(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: votes_user_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY votes
  ADD CONSTRAINT votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: votes_post_id_fkey; Type: FK CONSTRAINT;
--

ALTER TABLE ONLY votes
  ADD CONSTRAINT votes_post_id_fkey FOREIGN KEY (post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE RESTRICT;